version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: collection_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collection_db
    ports:
      - "5432:5432"
    volumes:
      - collection_db_data:/var/lib/postgresql/data

volumes:
  collection_db_data:
