export const PackageStatus = {
  TO_BE_PICKED_UP: "TO_BE_PICKED_UP",
  PICKED_UP: "PICKED_UP",
  ADDED_TO_BAG: "ADDED_TO_BAG",
  EN_ROUTE: "EN_ROUTE",
  ARRIVED: "ARRIVED",
  SCHEDULED_FOR_DELIVERY: "SCHEDULED_FOR_DELIVERY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELAYED: "DELAYED",
} as const;
