import { Request, Response } from "express";
import prisma from "../lib/prisma";

export const createPackage = async (req: Request, res: Response) => {
  try {
    const { fromAddress, toAddress, weight } = req.body;

    // Basic validation
    if (!fromAddress || !toAddress || !weight) {
      res.status(400).json({
        error: "fromAddress, toAddress and weight are required",
      });
      return;
    }

    if (typeof weight !== "number" || weight <= 0) {
      res.status(400).json({
        error: "weight must be a positive number",
      });
      return;
    }

    // Create the package in the database
    // trackingId is auto-generated by Prisma (uuid)
    const newPackage = await prisma.package.create({
      data: {
        fromAddress,
        toAddress,
        weight,
      },
    });

    // Return 201 Created with the new package
    // The customer gets the trackingId from this response
    res.status(201).json({
      message: "Package created successfully",
      trackingId: newPackage.trackingId,
      package: newPackage,
    });
  } catch (error) {
    console.error("Error creating package:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

export const getAllPackages = async (req: Request, res: Response) => {
  try {
    const packages = await prisma.package.findMany({
      orderBy: { createdAt: "desc" },
    });

    res.json({ packages });
  } catch (error) {
    console.error("Error fetching packages:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

export const getPackageByTrackingId = async (req: Request, res: Response) => {
  try {
    const trackingId = req.params.trackingId as string;

    const pkg = await prisma.package.findUnique({
      where: { trackingId },
    });

    if (!pkg) {
      res.status(404).json({ error: "Package not found" });
      return;
    }

    res.json({ package: pkg });
  } catch (error) {
    console.error("Error fetching package:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};
