export const ErrorCodes = {
  // Package errors
  PACKAGE_NOT_FOUND: "PACKAGE_NOT_FOUND",
  PACKAGE_ALREADY_BAGGED: "PACKAGE_ALREADY_BAGGED",
  PACKAGE_NOT_ARRIVED: "PACKAGE_NOT_ARRIVED",
  INVALID_PACKAGE_DATA: "INVALID_PACKAGE_DATA",

  // Bag errors
  BAG_NOT_FOUND: "BAG_NOT_FOUND",
  BAG_ALREADY_DELAYED: "BAG_ALREADY_DELAYED",
  INVALID_BAG_DATA: "INVALID_BAG_DATA",

  // Truck errors
  TRUCK_NOT_FOUND: "TRUCK_NOT_FOUND",
  TRUCK_ALREADY_DEPARTED: "TRUCK_ALREADY_DEPARTED",
  TRUCK_NOT_DEPARTED: "TRUCK_NOT_DEPARTED",
  TRUCK_ALREADY_DELAYED: "TRUCK_ALREADY_DELAYED",
  INVALID_TRUCK_DATA: "INVALID_TRUCK_DATA",

  // Region errors
  REGION_NOT_FOUND: "REGION_NOT_FOUND",

  // General errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
